In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]

In [8]:
np.array(my_list3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [19]:
np.random.rand(2)

array([0.65859076, 0.07280173])

In [20]:
np.random.rand(5,5)

array([[0.14656945, 0.27298437, 0.42634057, 0.26038035, 0.54310192],
       [0.47026121, 0.75787758, 0.50957336, 0.60794789, 0.66282193],
       [0.68424967, 0.67447474, 0.66223927, 0.41991371, 0.72286605],
       [0.12437231, 0.82876054, 0.50730808, 0.55409163, 0.90581591],
       [0.0201866 , 0.29162759, 0.78117215, 0.72081831, 0.29964815]])

In [21]:
np.random.randn(2)

array([ 0.95716294, -0.32136968])

In [22]:
np.random.randn(5,5)

array([[-1.16152788,  0.22604548, -0.28806509,  1.37149036, -0.49522418],
       [ 0.36120985, -0.13431306, -2.44291702,  0.82482828, -1.02081674],
       [-0.20747439, -1.13393818,  0.80685318,  0.762814  ,  0.54152223],
       [ 0.805019  , -0.37396496, -1.45163104,  0.3886069 ,  0.07867417],
       [ 0.162129  ,  0.36050048,  0.15448071,  0.17573768, -1.06645528]])

In [23]:
np.random.randint(1,100)

37

In [24]:
np.random.randint(1,100,10)

array([11, 47, 66, 79, 38, 11, 90, 86, 30,  5])

In [27]:
array_1d = np.array(my_list)
array_2d = np.array(my_matrix)
array_3d = np.array(my_list3)

In [28]:
array_1d.shape

(3,)

In [29]:
array_2d.shape

(3, 3)

In [30]:
array_3d.shape

(3, 3, 3)

In [57]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
arr.shape

(25,)

In [39]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [40]:
arr.reshape(1,25).shape

(1, 25)

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [43]:
arr.reshape(25,1).shape

(25, 1)

In [44]:
array_2d.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
array_2d.reshape(-1).shape

(9,)

In [48]:
array_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [49]:
array_3d.reshape(-1).shape

(27,)

In [50]:
b = [10,12,41,17,49,2,46,3,19,39]
ranarr = np.array(b)
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [51]:
ranarr.max()

49

In [52]:
ranarr.argmax()

4

In [53]:
ranarr.min()

2

In [54]:
ranarr.argmin()

5

In [55]:
arr.dtype

dtype('int32')

In [56]:
arr1 = np.linspace(0,10,10)
arr1.dtype

dtype('float64')

In [61]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr[8]

8

In [63]:
arr[1:5]

array([1, 2, 3, 4])

In [64]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [65]:
arr[0:10:2]

array([0, 2, 4, 6, 8])

In [66]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [68]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [71]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [72]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [73]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [74]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [75]:
arr_2d[1]

array([20, 25, 30])

In [76]:
arr_2d[1][0]

20

In [77]:
arr_2d[1,0]

20

In [78]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [79]:
arr_2d[:,2]

array([15, 30, 45])

In [81]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
[arr[2],arr[5],arr[9]]

[2, 5, 9]

In [83]:
arr[[5,9,2]]

array([5, 9, 2])

In [84]:
arr_2d[[0,2]]

array([[ 5, 10, 15],
       [35, 40, 45]])

In [87]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [89]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [90]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [92]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])